### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by BlackthornYugen** [SeaSharpe/Disposable#2]
This issue is pretty good.

**Comment by BlackthornYugen** [comment]
Lies :poop:

**Comment by ndahlquist-cc** [comment]
So we'd have one of these for each task?

**Comment by BlackthornYugen** [comment]
Yeah

**Comment by BlackthornYugen** [comment]
We might still want a ghant chart; not sure.

**Comment by ndahlquist-cc** [comment]
Probably wouldn't hurt if we can get a fairly comprehensive list of tasks
